### ISSUE TITLE
Final Exam

### ISSUE THREAD

**Issue by acradis** [Salok/Debates#4]
Lo abro para que podamos escribir cómodos en vez de con el teclado del móvil. Si al final terminamos discutiendo en Whatsapp pues nada pero aquí lo dejo por si acaso.

**Comment by acradis** [comment]
This is your final exam.

You have 60 hours.

Your solution must at least allow Harry to evade immediate death,
despite being naked, holding only his wand, facing 36 Death Eaters
plus the fully resurrected Lord Voldemort.

If a viable solution is posted before
*12:01AM Pacific Time* (8:01AM UTC) on Tuesday, March 3rd, 2015,
the story will continue.

Otherwise you will get a shorter and sadder ending.

Keep in mind the following:

1. Harry must succeed via his own efforts. The cavalry is not coming.
Everyone who might want to help Harry thinks he is at a Quidditch game.

2. Harry may only use capabilities the story has already mentioned;
he cannot develop wordless wandless Legilimency in the next 60 seconds.
Of course, Harry may find more clever ways to use abilities
he has already been established to have.

3. Voldemort is evil and cannot be persuaded to be good;
the Dark Lord's utility function cannot be changed by talking to him.

4. If Harry raises his wand or speaks in anything except Parseltongue,
the Death Eaters will fire on him immediately.

5. If the simplest timeline is otherwise one where Harry dies -
if Harry cannot reach his Time-Turner without Time-Turned help -
then the Time-Turner will not come into play.

6. It is impossible to tell lies in Parseltongue.

Within these constraints,
Harry is allowed to attain his full potential as a rationalist,
now in this moment or never,
regardless of his previous flaws.

Of course 'the rational solution',
if you are using the word 'rational' correctly,
is just a needlessly fancy way of saying 'the best solution'
or 'the solution I like' or 'the solution I think we should use',
and you should usually say one of the latter instead.
(We only need the word 'rational' to talk about ways of thinking,
considered apart from any particular solutions.)

And by Vinge's Principle,
if you know exactly what a smart mind would do,
you must be at least that smart yourself.

So what I mean in practice,
when I say Harry is allowed to attain his full potential as a rationalist,
is that Harry is allowed to solve this problem
any way YOU would solve it.
If you can tell me exactly how to do something,
Harry is allowed to think of it.

But it does not serve as a solution to say, for example,
"Harry should persuade Voldemort to let him out of the box"
if you can't yourself figure out how.

The rules on Fanfiction dot Net allow at most one review per chapter.
Please submit *ONLY ONE* review of Ch. 113, to submit one suggested solution.

For the best experience, if you have not already been following
Internet conversations about recent chapters, I suggest not doing so,
trying to complete this exam on your own,
not looking at other reviews,
and waiting for Ch. 114 to see how you did.

I wish you all the best of luck, or rather the best of skill.

Ch. 114 will post at 10AM Pacific (6PM UTC) on Tuesday, March 3rd, 2015.

**Comment by acradis** [comment]
En lo que me baso:

A   112: (en parsel)
"Ssilence, fool. Remain ssilent unlesss given leave by me to sspeak. Keep your wand pointed down and do not raisse it unlesss told. Elsse you die upon the sspot, and mark that I ssaid that in Parsseltongue." Voldemort reached into the altar again.

B   113 : (en ingles)
[Voldie]: Now I shall ask Harry Potter one final question, and he is to answer that question for my ears alone, in Parseltongue. Strike the boy down at once if he answers with anything but hisses, if he tries to speak one word of human speech.

C  113: (en parsel)
[Voldie]: The Muggle Artss I have now learned of from you, and I am already sstudying them

D  113: (en parsel)
[Voldie]: For each unknown power you tell me how to masster, or other ssecret you tell me that I desire to know, you may name one more of thosse to insstead be protected and honored under my reign. Thiss alsso I promisse and intend to keep."

E 113 (inglés pero es un UV):
"I vow..." Harry said. His voice shook, but he spoke. "That I shall not... by any act of mine... destroy the world... I shall take no chances... in not destroying the world... if my hand is forced... I may take the course... of lesser destruction over greater destruction... unless it seems to me that this Vow itself... leads to the world's end... and the friend... in whom I have confided honestly... agrees that this is so.

F 107 (parsel):
"By the by, have you betrayed me yet?" said Professor Quirrell.
"Have not betrayed you yet," Harry hissed.

**Comment by acradis** [comment]
Lo que haría si fuese Harry

Notas:
1.  No puedo usar Partial Transfiguration porque Voldie ha puesto wards (no me gusta la palabra custodias) por la zona.
2.  No hay hechizos anti-aparición ni anti-time-turner a no ser que Voldie los haya puesto sin hablar. 
3.  A Voldie le interesa la ciencia muggle.
4.  Es probable que mi varita esté encantada (por A)
5.  Si tomamos  lesser destruction de forma literal puedo hacer varias cosas (matar a toda la raza humana pues están hiriendo a la naturaleza, destruir el sol pues está hiriendo a los átomos, destruir cualquier astro por razones similares, etc)
6.  No creo que todo sea un truco del espejo porque eso sería cutre

Qué hacer:
1.  Darle el nombre de un libro de ciencia el cual le sería útil aprender (sobre electromagnetismo por ejemplo)
2.  Nombrarme a mí mismo como persona que Voldie debe proteger y honrar. (no se si mi nombre es Tom Riddle o Harry Potter perono importa porque pregunto)
3.  Darle info de ciencia (o en caso de que diga en parsel que ya no le interesa, de otra cosa: la traición de Lucius, alguna magia interesante, etc) y proteger a quien me preocupe en caso de que mi plan no funcione (padres, estudiantes, etc)
4.   Informar de que no me está honrando al encantar mi varita (la desencanta pues el parsel le obliga)
5.  Informar que no me está honrando reteniéndome aquí (quita el hechizo anti-time-turner)
6.  Lanzo un hechizo que hiera (preferiblemente mate) a Mr Grim
7.  Todos los necrófagos me atacan pues no he hablado parsel
8.  Voldie me protege (no sé si de forma defensiva o atacando a los necrófagos)
9.  Hago Accio Time Turner y me voy 6 horas al pasado (dejo a Hermione porque no sé cómo funciona lo de revivir y viajar en el tiempo a la vez)
10. Le explico a McGonagall ( o a otro profesor) lo que ocurrira
11. Le doy una carta encriptada usando historias scifi y de fantasia muggles explicando lo que ocurrirá a mi yo del pasado y hago que McGonagall le haga salir de Hogwarts (asi no aparecerá en el Marauders Map)
12. Recibo la carta falsa y me dirijo al tercer piso. Paso todas las pruebas respondiendo siempre igual que la primera vez y actuando como si no supiese lo siguiente (como antes dije “yet”, el parsel me permitirá “mentir”)
13. Cuando llegue hasta el espejo y me encuentre con Dumbledore, le contare lo necesario para que en vez de encarcelarse a sí mismo, encarcele a Quirrel.  Para más control, me mostraré yo mismo en vez de dejar que Quirrel me quite la capa y aturda mentalmente a Dumbledore con mi presencia

Grandes saltos en mi razonamiento:
1.  Puede que lo de honrar no pueda tomarlo tan literal como para que Voldie me permita usar la varita.
2.  Puede que McGonagall no haga bien su papel e informe a Dumbledore en vez de llevarse a mi otro yo consigo.
3.  Si no  consigo matar a Grim, no sé cómo me afectará el UV en el pasado/futuro.

**Comment by Jsevillamol** [comment]
Datos:
*La clave para solucionar el entuerto está en la promesa que Voldie acaba de hacer.
*Poderes que solo Harry domina: transfiguración parcial. Eso nos da una persona a proteger.
Mi solución:
*Harry revela la transfiguración parcial y elige protegerse a sí mismo.

Otras vías de investigación:
*Algún uso de la transfiguración parcial que confunda a los Death Eaters y Voldie. 
*Convencer a Voldie de que él es el único que puede salvar el mundo (?)

**Comment by acradis** [comment]
No creo que se pueda usar transfiguracion parcial por las wards.
No creo que deba informar de esa capacidad
Coincido en que la ultima promesa es crucial y en que debe nombrarse a sí mismo

En caso de usar la transfiguración parcial:
1. Transfigurar algún fluido corporal de voldie y los necrófagos en droga.
2. afectar  a las varitas de todos los malos.

**Comment by Jsevillamol** [comment]
Imposible. Se necesita una distacia corta, y le lleva tiempo hacer las transfiguraciones. En 60 segundos podrá hacer una.

**Comment by Jsevillamol** [comment]
Por cierto, no puede informar a su yo del pasado si no recuerda haber sido informado.

**Comment by acradis** [comment]
pues no le informo, me deshago de él (ie hago que se quede con mcgonagall y luego lo llevo a donde vaya a terminar la escena) y le sustituyo

**Comment by acradis** [comment]
antes de viajar en el tiempo hago Accio Pouch y luego viajo en el tiempo a la par que digo que salga Harry. En el pasado, hago que alguien (McGonagall) le aturda y meta en el pouch. 

Si esto no vale pues me meto yo en el pouch con la regla de salir cuando digan alguna frase de la conversacion con dumbledore (aunque mi yo pasado me vería en este caso asi que tiene que ser en un momento que sepa que no estaba mirando en la dirección del  pouch especificamente)

**Comment by acradis** [comment]
Al final esto es lo que he mandado

I cant use partial transfiguration because of the wards
This is what Id do:
1.Ask Voldie to let me say the names I choose to be protected in human speech without the deatheaters attacking me.
2. Give him info of a book about science (about electromagnetism for example)
3. Name myself
4. Repeat and name the Hogwarts teachers and students who might be useful in battle
5. Inform him that he is not honoring me by keeping me there and not allowing me to use my magic (if he had enchantments on the wand he´ll Finite them).
6. Attack (magically) Mr Grim trying to kill him
7. The DE attack and Voldie must protect me
8. Accio time-turner
9. Look to the sky and shout some random  word,(for example Pumpkin)
10. Time turn back to the time of receiveng the false letter
11. Look for the named people
12. Look for my past self, block his senses and introduce all the people and myself in the pouch
13. My past self acts normally (Dumbledore loses, Hermione is revived) and when he shouts "Pumpkin" all of us attack the DE and Voldie

Flaws: If the marauder maps sees inside the puch we lose
If the senses blocking spell does not exist, we cant act
I dont know what to do with the unbreakable vow

y luego otro mensaje en el que decia que Pumpkin era la contraseña para salir del pouch (me olvide de escribirlo en el primero)

**Comment by Jsevillamol** [comment]
The exam finished long ago. Closing.
